
<?php

// This file is generated by Composer
require_once 'vendor/autoload.php';
require_once 'mysqli_connect.php';

$github = new \Github\Client();

//$repositories = $client->api('user')->repositories('ornicar');
function gist_single_download_link() {
    global $github;
    $gist = $github->api('gists')->show('52dec455094a60a5db49');
    var_dump($gist);

    $download_link = '<a href="http://gist.github.com/' . $gist['owner']['login'] . '/' . $gist['id'] . '/archive/' . $gist['history'][0]['version'] . '.zip">Download</a>';

    echo $download_link;
}

function all_public_private_gist_list() {
    global $github, $db_connect;
    $github->authenticate($_POST['user_name'], $_POST['password']);
    $gist_all = $github->api('gists')->all($_POST['user_name']);
    $gist_all_count = count($gist_all);
    $counter = 1;
    $sql = "INSERT INTO all_gist (gist_id, description, category, user_name, last_version, download_link) VALUES ";
    foreach ($gist_all as $gist) {
        $gist_id = $gist['id'];
        $gist_description = $gist['description'];
        $user_name = $gist['owner']['login'];
        $last_version = $github->api('gists')->show("$gist_id")['history'][0]['version'];
        $download_link = 'http://gist.github.com/'.$user_name.'/'.$gist_id.'/archive/'.$last_version.'.zip';
        $sql .= "('$gist_id', '$gist_description', '', '$user_name', '$last_version', '$download_link')";
        if ($counter != $gist_all_count) {
            $sql .= ', ';
        }
        $counter++;
    }
    $result_insert = mysqli_query($db_connect, $sql);
    if ($result_insert) {
        echo 'Result inserted successfully.';
    }
}

//gist_single_download_link();
all_public_private_gist_list();
?>